### ISSUE TITLE
[Addition for Jury Section: Neil Gough]

### ISSUE THREAD

**Issue by ds-888** [hackcambridge/camvscovid-issues#4]
**Describe what would you like to add**
Next member of the jury

**Content**
Neil Gough
Visiting Fellow in Marketing
Judge Business School
http://www.csap.cam.ac.uk/network/neil-gough/

Thank you!

**Comment by vanjo9800** [comment]
Cannot find a good enough picture of Neil unfortunately. Let's see how this one goes and maybe we can ask him?
